language: python
python:
    - 2.7
before_install:
    - date -u
    - uname -a
    - lsb_release -a
    - sudo add-apt-repository ppa:openscad/releases -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install openscad libfreetype6-dev xvfb
install:
    - pip install coveralls coverage
    - python setup.py install
script:
    - Xvfb :5 -screen 0 800x600x24 &
    - DISPLAY=:5 nosetests --with-coverage --cover-package=scad
after_success:
    - coveralls
