language: python
python:
    - 2.7
before_install:
    - date -u
    - uname -a
    - lsb_release -a
    - sudo add-apt-repository ppa:openscad/releases -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install openscad libfreetype6-dev
install:
    - python setup.py install
script:
    - nosetests
